# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json
PackageIdentifier: danzerzine.LayoutFox
PackageVersion: 1.0.6
PackageLocale: ru-RU
PackageName: LayoutFox
ShortDescription: Автопереключатель раскладки RU/EN, который видит и нажатия через Parsec.
Description: |-
  LayoutFox исправляет текст, набранный не в той раскладке, и переключает раскладку прямо при наборе.
  В отличие от многих переключателей, видит и нажатия, которые приходят через Parsec с другого компьютера.
ManifestType: locale
ManifestVersion: 1.12.0
